version: "3"

services:
  database:
    image: mysql
    container_name: test_db
    environment:
      - MYSQL_DATABASE=test_db
      - MYSQL_ROOT_HOST=%
      - MYSQL_ROOT_PASSWORD=1234
    command: ['--character-set-server=utf8mb4', '--collation-server=utf8mb4_unicode_ci']
    ports:
      - "3306:3306"
    networks:
      - test_network
  application:
    build:
      dockerfile: Dockerfile
      context: .
    #restart: always
    ports:
      - "8080:8080"
    depends_on:
      - database
    container_name: app_test
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://database:3306/testdb?useSSL=false&serverTimezone=UTC&useLegacyDatetimeCode=false&allowPublicKeyRetrieval=true
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: 1234
    networks:
      - test_network
networks:
  test_network:
